# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39d48f05d7b745f985b13967779c3900"
name = "awesome-app"
handle = "awesome-app-21"
application_url = "https://diagnostic-house-representing-injuries.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "enr-products-test.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://diagnostic-house-representing-injuries.trycloudflare.com/auth/callback",
  "https://diagnostic-house-representing-injuries.trycloudflare.com/auth/shopify/callback",
  "https://diagnostic-house-representing-injuries.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
